version: '3.9'

services:
  db:
    image: mysql:8.0
    restart: on-failure
    command: [ '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
    environment:
      - DB_ROOT_PASSWORD=peer-review-data_root_pw
      - DB_HOST=peer-review-data_db
      - DB_PORT=3306
      - DB_NAME=peer-review-data
      - DB_USER=peer-review-data
      - DB_PASSWORD=peer-review-data_pw
    entrypoint: [ 'docker-entrypoint.sh', '--default-authentication-plugin=mysql_native_password' ]
    ports:
      - "5555:3306"
    volumes:
      - ./.data/mysql:/var/lib/mysql:delegated
      - ./mysql:/docker-entrypoint-initdb.d:ro
    container_name: peer-review-data_db
  main:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    env_file:
      - .env
    container_name: peer-review-data_main
    volumes:
      - ./:/app
